ngtcp2/nghttp3

- .travis.yml
- CMakeLists.txt
- CMakeOptions.txt
- cmake/ExtractValidFlags.cmake
- cmake/FindCUnit.cmake
- cmake/Version.cmake
- cmakeconfig.h.in
- configure.ac
- examples/CMakeLists.txt
- lib/CMakeLists.txt
- lib/includes/CMakeLists.txt
- tests/CMakeLists.txt
Similar to https://github.com/ngtcp2/ngtcp2/pull/45, this adds CMake support. Main motivation for this is being able to build ngtcp2+nghttp3 out-of-tree such that I can create a draft -19 test capture.
> CMake support

- lib/includes/nghttp3/nghttp3.h
To better emphasize to what context this user data is associated, as
there are several other user data pointers involved in the API as well.
> nghttp3.h: use conn_user_data instead of just user_data

- lib/nghttp3_ringbuf.c
This commit changes ngtcp2 to nghttp3 to be consistent with other
header and source files.
> Change nghttp3_ringbuf.c "title" to nghttp3

- lib/CMakeLists.txt
- lib/nghttp3_ringbuf.c
Hi,
a simple modification to enable the Windows build that does not necessarily embed __builtin_popcount and need to be linked against WinSock2 for utility functions like ntohs.
I based this on ngtcp2 development (see ngtcp2/lib/ngtcp2_ringbuf.c commit 119f88ce06b68dd7beeb173039151c4a187cb696)
> Restore Windows build for the nghttp3 library

- lib/nghttp3_qpack.h
This commit updates the comment for the `nghttp3_qpack_context` struct's
member `max_dtable_size.
> Update max_dtable_size comment for qpack_context

- lib/nghttp3_conn.c
When the default case is reached, 'rv' may be read without being initialized.
> Fix read from uninitialized variable

- lib/nghttp3_ringbuf.c
This state where we pass NULL to memcpy() is reached in the tests and has an undefined behavior.
> Don't call memcpy() with NULL src

- lib/CMakeLists.txt
- lib/nghttp3_conv.h
On Windows, the `ntonl` family of functions is declared in `Winsock.h` and defined in `ws2_32.lib`. The nghttp3 library doesn't include `Winsock.h` anywhere, so the usage of these `ntonl` functions was causing an implicit reference to these functions using the wrong calling convention (`__cdecl` instead of `__stdcall`). Later, when linking `nghttp3_static.lib` into an application (e.g. `curl`), these undefined references couldn't be resolved due to the signature mismatch:
```
1>nghttp3.lib(nghttp3_conv.obj) : error LNK2001: unresolved external symbol _htonl
1>  Hint on symbols that are defined and could potentially match:
1>    _htonl@4
```
Note: `_htonl` is the cdecl version of `htonl`, whereas `_htonl@4` is the stdcall version.
This change adds definitions for the `ntonl` family of …
> Fix ntonl linking errors on Windows

- lib/includes/nghttp3/nghttp3.h
- lib/nghttp3_conn.c
- lib/nghttp3_qpack.c
- tests/nghttp3_qpack_test.c
size_t is 32-bit on 32-bit machines and min_dtable_update was assigned NGHTTP3_QPACK_INT_MAX, which is 64 bits. This failed the tests on 32-bit machines.
There are a few other places in nghttp3_qpack where uint64_t values are assigned to size_t variables and need to be fixed.
> Fix overflow of min_dtable_update

- CMakeLists.txt
When using `CMake` to build nghttp3, the definition of `ssize_t` is incorrect for 64-bit builds. It's defined as an `int`, which at least on Windows is a 32-bit type.
What this means is that any nghttp3 function that returns an error code ends up returning a bit pattern that, on 64-bit builds, is interpreted by the caller as a _large positive number_ instead of a _small negative number_. That's because the caller (e.g. libcurl) will probably have a different definition of `ssize_t`, one that is correctly sized as a signed 64-bit integer, not a signed 32-bit integer.
See https://github.com/ngtcp2/ngtcp2/pull/193 for more info.
> Fix definition of ssize_t in CMake for 64-bit builds

- CMakeOptions.txt
- lib/CMakeLists.txt
* static lib suffix can be controlled via STATIC_LIB_SUFFIX variable
* this solution is the same as already implemented in nghttp2
> cmake: add ENABLE_STATIC_LIB option to build a static library

- examples/qpack_decode.cc
I got this error when trying to compile on Fedora 34:
```
qpack_decode.cc: In member function ‘std::tuple<std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, int> nghttp3::Decoder::read_request(nghttp3_buf*, int64_t)’:
qpack_decode.cc:99:19: error: conversion from ‘<brace-enclosed initializer list>’ to ‘std::tuple<std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, …
```
> Fixed ambiguous type when returning a tuple

- doc/source/qpack-howto.rst
There is a small typo in doc/source/qpack-howto.rst.
Should read `pointer` rather than `poitner`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, poitner -> pointer

- lib/includes/nghttp3/nghttp3.h
- lib/nghttp3_conn.c
- tests/nghttp3_conn_test.c
Add fin parameter to nghttp3_end_headers callback to tell an
application that the stream has ended with this header block.
Previously, the application cannot know the stream has ended or not
and has to wait for nghttp3_end_stream callback to be invoked or
proceed as if the message might have a body.  This is not really
useful because if one chooses latter, you might need
transfer-encoding: chunked when forwarding the request in HTTP/1.1 hop
even if the method is GET.
> Add fin parameter to nghttp3_end_headers callback

- CMakeLists.txt
In MSVC the regex replace of compiler flags for a release build caused some flags to be fused together, `/Gy/Z7`, which resulted in the following error.
`cl : Command line error D8016 : '/O2' and '/GZ' command-line options are incompatible`
Took the same section from nghttp2's CMakeLists which contains a space to fix the issue.
> Fix regex replace of compiler flags

- lib/nghttp3_mem.c
- lib/nghttp3_mem.h
- lib/nghttp3_qpack.c
- lib/nghttp3_rcbuf.c
- lib/nghttp3_rcbuf.h
nghttp3_rcbuf now stores nghttp3_mem in its field.  The nghttp3_mem
object must be kept as long as nghttp3_rcbuf object exists.
> nghttp3_rcbuf now stores nghttp3_mem in its field

- lib/nghttp3_http.c
RFC9110 Section 16.3.2 states that each header field specification
needs to document that whether or not the header field is allowed in
trailers, and by default it will not be allowed.  RFC9218 does not say
anything about trailers, which means that priority header field is not
allowed in trailers.  Therefore, we ignore priority header field.
> Ignore priority header field in trailer fields

- lib/nghttp3_http.c
- tests/main.c
- tests/nghttp3_http_test.c
- tests/nghttp3_http_test.h
Do not allow leading or trailing SPC or HTAB in a field value, as per
https://datatracker.ietf.org/doc/html/rfc9113#section-8.2.1
It is HTTP/2 specification, but I think it can be applicable to HTTP/3
as well.
> Do not allow leading or trailing SPC or HTAB in a field value

- lib/nghttp3_http.c
No need to check pseudo header lws because it is guaranteed not to
have trailing white spaces.
> No need to check pseudo header lws

- lib/nghttp3_conn.c
- lib/nghttp3_stream.h
- tests/main.c
- tests/nghttp3_conn_test.c
- tests/nghttp3_conn_test.h
Treat NGHTTP3_ERR_MALFORMED_HTTP_HEADER as stream error and ask QUIC
stack to send STOP_SENDING and RESET_STREAM to the stream.
Previously, this error is treated as a connection error.
> Treat NGHTTP3_ERR_MALFORMED_HTTP_HEADER as stream error

- .github/workflows/build.yml
GitHub Actions suddenly refused to install wine32 because of broken
dependencies.  In order to workaround this issue, do not run tests on
i686-w64-mingw32 host.
> Run tests for x86_64-w64-mingw32 host only

- lib/includes/nghttp3/nghttp3.h
- lib/nghttp3_conn.c
Do not return NGHTTP3_ERR_STREAM_NOT_FOUND from
nghttp3_conn_get_frame_payload_left, and just return 0 if a stream is
not found.
> nghttp3_conn_get_frame_payload_left: Avoid NGHTTP3_ERR_STREAM_NOT_FOUND

- lib/includes/nghttp3/nghttp3.h
- lib/nghttp3_conn.c
Do not return NGHTTP3_ERR_STREAM_NOT_FOUND from the following
functions:
- nghttp3_conn_add_write_offset
- nghttp3_conn_add_ack_offset
- nghttp3_conn_block_stream
- nghttp3_conn_shutdown_stream_write
- nghttp3_conn_unblock_stream
- nghttp3_conn_resume_stream
- nghttp3_conn_close_stream
In general, we simply ignore NGHTTP3_ERR_STREAM_NOT_FOUND from these
functions.  Then it would be better to treat it success and remove the
need for the error handling.
> Avoid NGHTTP3_ERR_STREAM_NOT_FOUND

- lib/includes/nghttp3/nghttp3.h
- lib/nghttp3_conn.c
nghttp3_conn_close_stream needs NGHTTP3_ERR_STREAM_NOT_FOUND so that
an application can reliably extend stream limit if a stream is not
handled by nghttp3.
> nghttp3_conn_close_stream needs NGHTTP3_ERR_STREAM_NOT_FOUND

- lib/nghttp3_ringbuf.c
Fix __popcnt with Windows ARM (32 bits) 
found via https://github.com/microsoft/vcpkg/pull/26497
> nghttp3_ringbuf: fix __popcnt with WIN ARM (32bits)

- lib/nghttp3_conv.h
Identical patch to the ones merged earlier to ngtcp2 and nghttp2:
https://github.com/ngtcp2/ngtcp2/pull/601
https://github.com/nghttp2/nghttp2/pull/1822
> add casts to silence implicit conversion warnings

- lib/includes/nghttp3/nghttp3.h
- lib/nghttp3_qpack.c
- tests/main.c
- tests/nghttp3_qpack_test.c
- tests/nghttp3_qpack_test.h
Allow application to specify which field should be indexed by including NGHTTP3_NV_FLAG_TRY_INDEX in nghttp3_nv.flags.  This is just a hint, and QPACK encoder might not index it in various reasons.
Fixes #100
> Allow application to specify which field should be indexed by QPACK

- lib/nghttp3_stream.c
Increase stream outq capacity because the previous value is too small for high latency network.  As the comment suggests, we should provide a knob for an application to set this limit.
> Increase stream outq capacity

- lib/nghttp3_stream.c
- lib/nghttp3_stream.h
Remove stream outq limit by the library.  Instead, let an application manage the amount of buffer they can burn because the most of the items in outq is data provided by the application.  For example, the application can track the number of bytes it has provided to the library in nghttp3_read_data_callback.  If it exceeds the limit, return NGHTTP3_ERR_WOULDBLOCK from the callback.  The tracked bytes should be updated when the data is acknowledged (see nghttp3_acked_stream_data callback).
> Remove stream outq limit

- lib/nghttp3_ringbuf.c
When building on Windows with clang for ARM targets, `__popcnt` is defined.
> Clang has __popcnt for ARM

- lib/includes/nghttp3/nghttp3.h
- lib/nghttp3_conn.c
- lib/nghttp3_http.c
- tests/nghttp3_http_test.c
Use uint8_t for bool fields to potentially reduce space.
> Use uint8_t for bool fields

- examples/CMakeLists.txt
Fix the link failure when shared library is disabled but static library is available.
Fixes #127
> cmake: Fix static link failure in examples

- lib/includes/nghttp3/nghttp3.h
- lib/nghttp3_conn.c
- tests/nghttp3_conn_test.c
Add nghttp3_recv_settings callback which is invoked when SETTINGS frame is received.
This commit fixes the issue that rstate is not reset when entire SETTINGS is read, instead it is reset when a next frame is received.
> Add nghttp3_recv_settings callback

- lib/nghttp3_conv.h
- Only define nghttp3_bswap64 for little endian platform.
- Use _byteswap_uint64 for win32.
- Use OSSwapInt64 for apple platform.
> Tweak nghttp3_ntohl64/nghttp3_htonl64 definitions

- lib/includes/nghttp3/nghttp3.h
- lib/nghttp3_conn.c
Remove nghttp3_conn_is_remote_qpack_encoder_stream which was introduced along with nghttp3_conn_get_frame_payload_left, but not used effectively.
> Remove nghttp3_conn_is_remote_qpack_encoder_stream

- lib/nghttp3_conv.h
Summary:
Fix compile error for Android/Linux - undefined symbol: nghttp3_ntohl
Summary:
Found the following compile error when we build the latest nghttp3 for Android/Linux.
```
ld.lld: error: undefined symbol: nghttp3_ntohl >>> referenced by nghttp3_conv.c:58 (third-party/nghttp3/lib/nghttp3_conv.c:58) >>> ../nghttp3#compile-pic-nghttp3_conv.c.o2a37e81d,platform010-clang/lib/nghttp3_conv.c.o:(nghttp3_get_varint)
```
nghttp3_ntohl is not a function or macro. We should use ntohl instead which is also part of previos logic in #135.
Test Plan:
Compile and check no error.
Reviewers:
Subscribers:
Tasks:
Tags:
> Fix compile error for Android/Linux - undefined symbol: nghttp3_ntohl

- lib/nghttp3_conn.c
- lib/nghttp3_conn.h
- lib/nghttp3_ksl.c
- lib/nghttp3_ksl.h
- lib/nghttp3_objalloc.h
- lib/nghttp3_stream.c
- lib/nghttp3_stream.h
Do not inline nghttp3_objalloc_*_get because it fails on some platforms.
> Do not inline nghttp3_objalloc_*_get

- lib/nghttp3_unreachable.h
Use __FILE_NAME__ instead of __FILE__ not to include a full source file path.
> Use __FILE_NAME__ instead of __FILE__

- CMakeLists.txt
- CMakeOptions.txt
- lib/CMakeLists.txt
Add a new option `BUILD_TESTING` to control whether or not the library is built with testing. Also fix a library naming conflict when building both static and shared libraries in MSVC by setting a default of `_static` for `STATIC_LIB_SUFFIX`.
> cmake: add BUILD_TESTING, fix MSVC with static + shared

- lib/nghttp3_macro.h
Running `make clang-format` updates nghttp3_macro.h format. 
This PR updates the repo with the format changes.
> Fix format in nghttp3_macro.h

- lib/nghttp3_conn.c
- lib/nghttp3_idtr.c
- lib/nghttp3_idtr.h
Remove server field because it is only used in assertion.
> nghttp3_idtr: Remove server field

- lib/CMakeLists.txt
Fix include export
@tatsuhiro-t @vszakats 
I fix it according to vcpkg review:
https://github.com/microsoft/vcpkg/pull/40673
> Fix include export

- lib/nghttp3_qpack.c
Do huffman encoding only when the reduction is more than 25% because huffman decoding is quite costly for relatively large field values.
> Do huffman encoding only when the reduction is more than 25%

- README.rst
- lib/nghttp3_http.c
- tests/nghttp3_http_test.c
Optimize nghttp3_check_header_value with AVX2 instructions if available.
> Optimize nghttp3_check_header_value

- lib/nghttp3_conn.c
Vanilla HTTP/3 does not allow server to create bidirectional stream. libnghttp3 expects that application configures the QUIC stack like so. Still it would be nice to explicitly deny new server-initiated bidirectional stream for clarity.
> Explicitly deny new server-initiated bidirectional stream

- lib/nghttp3_gaptr.c
In practice, we never pass the number larger than NGHTTP3_MAX_VARINT, but it should check whether the iterator is beyond the range as an API contract.
> nghttp3_gaptr: Check iterator

- lib/nghttp3_gaptr.c
Assert !nghttp3_ksl_it_end in nghttp3_gaptr_is_pushed just like we do in the other functions
> nghttp3_gaptr: Assert !nghttp3_ksl_it_end

- lib/nghttp3_qpack.c
decoder->rstate.name and decoder->rstate.value are nullified after processing each encoder instruction.  If they need to be kept, their reference count should be nonzero, and stored in the dynamic table. This null deference occurs when memory allocation fails.
> Fix null dereference

- lib/includes/nghttp3/nghttp3.h
- lib/nghttp3_conn.c
The preceding assertion for nghttp3_client_stream_bidi() ensures that nghttp3_stream_uni() always returns false.
> Remove redundant condition in nghttp3_conn_submit_request()

- lib/nghttp3_conn.c
My HTTP3 client receives a grease frame from [quiche](https://github.com/cloudflare/quiche/blob/master/quiche/src/h3/mod.rs#L2089) and it includes a fin.
```
STREAM id=15 fin=1 off=0 len=26 dir=Unidirectional origin=Server-initiated
Frame Type: STREAM (0x000000000000000f)
Stream ID: 15
Offset: 0
Length: 26
Stream Data: f739d7873c274c684752454153452069732074686520776f7264
```
after running gdb I see that nghttp3 does `nghttp3_conn_read_uni` and then identifies `stream->type` is `NGHTTP3_STREAM_TYPE_UNKNOWN` and proceeds with `conn_call_stop_sending`.
Looking at [RFC9114 Reserved Stream Types](https://datatracker.ietf.org/doc/html/rfc9114#stream-grease)
> Endpoints MUST NOT consider these streams to have any meaning upon receipt.
If I understand this right, maybe it is never a good idea to …
> Avoid STOP_SENDING for unknown stream type in case fin is set.

- CMakeLists.txt
- CMakeOptions.txt
- lib/nghttp3_ringbuf.c
ENABLE_POPCNT is on by default, so the existing logic will not be affected.
> Add a CMake option to support disabling the popcnt instruction

- lib/nghttp3_stream.c
If QUIC stack works properly, we never get any data on closed stream. But the fuzzer currently does not check the stream state.
> Fix fuzzer failure

- lib/nghttp3_conn.c
- lib/nghttp3_frame.c
- lib/nghttp3_frame.h
- lib/nghttp3_stream.c
- tests/nghttp3_conn_test.c
- tests/nghttp3_test_helper.c
- tests/nghttp3_test_helper.h
We only use length when writing a frame.  Directly pass the computed the length of the frame payload to the encoder function without setting it to nghttp3_frame_hd struct.  Now nghttp3_frame_hd is only used in tests.
> Remove length from nghttp3_frame

- lib/nghttp3_conn.c
- lib/nghttp3_conn.h
- lib/nghttp3_stream.h
- tests/nghttp3_conn_test.c
Previously, an nghttp3_stream that is blocked by QPACK is not deleted on QUIC stream closure, and it is deleted once it is unblocked.  But once QUIC stream is closed, we have nothing to do after receiving complete QPACK block.  This change just cancel QPACK, and deletes the nghttp3_stream once QUIC stream is closed even if it is blocked by QPACK.
> Delete a stream that is blocked by QPACK on QUIC stream closure

- lib/nghttp3_ksl.h
nghttp3_ksl.h could be used from C++ code which requires explicit cast.
> Revert #395 partially

- CMakeLists.txt
- CMakeOptions.txt
- lib/nghttp3_ringbuf.c
Resolves #399 . This PR removes all POPCNT intrinsic usage from the debug-only ispow2 helper in nghttp3_ringbuf.c, replacing it with the canonical bitwise power-of-two test: n && !(n & (n - 1)). This resolves crashes on CPUs without POPCNT while preserving performance.
•	ispow2 used POPCNT intrinsics under #ifndef NDEBUG.
•	CMakeLists.txt strips -DNDEBUG from Release-like builds, so the code executed everywhere.
•	On CPUs lacking POPCNT, the intrinsic produced an illegal instruction fault.
•	The bitwise formulation is architecture-neutral, constant-time, and emits just a few basic instructions.
•	For a single power-of-two check, POPCNT provides negligible benefit versus its complexity.
•	Avoids runtime CPUID dispatch and platform-specific branches.
•	Eliminates risk of crashes on older or …
> Replace POPCNT-based ispow2 with portable bitwise implementation to prevent illegal instruction crashes
